### ISSUE TITLE
Retrieve exception in `run_handle_interrupt`

### ISSUE THREAD

**Issue by vkottler** [vkottler/vcorelib#56]
```
vkottler@beelink1:~/workspace/runtimepy (dev/tui-upgrade) $ ./venv3.8/bin/runtimepy tui
Traceback (most recent call last):
  File "./venv3.8/bin/runtimepy", line 8, in <module>
    sys.exit(main())
  File "/home/vkottler/workspace/runtimepy/runtimepy/entry.py", line 76, in main
    result = entry(args)
  File "/home/vkottler/workspace/runtimepy/runtimepy/app.py", line 27, in entry
    return COMMAND(args)
  File "/home/vkottler/workspace/runtimepy/venv3.8/lib/python3.8/site-packages/vcorelib/args/__init__.py", line 51, in call_command
    return commands[args.command](args)
  File "/home/vkottler/workspace/runtimepy/runtimepy/commands/tui.py", line 41, in tui_cmd
    getattr(_curses, "wrapper")(start, args)
  File "/usr/lib/python3.8/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/vkottler/workspace/runtimepy/runtimepy/commands/tui.py", line 35, in start
    _run_handle_interrupt(task.run(window), eloop)
  File "/home/vkottler/workspace/runtimepy/venv3.8/lib/python3.8/site-packages/vcorelib/asyncio/__init__.py", line 47, in run_handle_interrupt
    shutdown_loop(eloop)
  File "/home/vkottler/workspace/runtimepy/venv3.8/lib/python3.8/site-packages/vcorelib/asyncio/__init__.py", line 21, in shutdown_loop
    eloop.run_until_complete(eloop.shutdown_asyncgens())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/vkottler/workspace/runtimepy/runtimepy/task/__init__.py", line 146, in run
    self.enabled.raw.value &= await _asyncio.shield(
  File "/home/vkottler/workspace/runtimepy/venv3.8/lib/python3.8/site-packages/vcorelib/asyncio/__init__.py", line 45, in run_handle_interrupt
    result = eloop.run_until_complete(to_run)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/vkottler/workspace/runtimepy/runtimepy/tui/task.py", line 36, in dispatch
    await self.tui.handle_char(window.getch())
KeyboardInterrupt
asyncio                              - ERROR  - Task exception was never retrieved
future: <Task finished name='Task-1' coro=<AsyncTask.run() done, defined at /home/vkottler/workspace/runtimepy/runtimepy/task/__init__.py:124> exception=KeyboardInterrupt()>
```

We seem to occasionally hit this

**Comment by vkottler** [comment]
Yeah I'm not really sure how to fix this. I think we just need to move beyond Python

**Comment by vkottler** [comment]
Was able to sort this out
